stages:
  - test
  - build
  - deploy

variables:
  NODE_VERSION: 16.16.0
  WORK_ENVIRONMENT: $CI_COMMIT_REF_SLUG

########################################
# build
########################################
.node-myroom-editor-build: &node-myroom-editor-build
  image: node:$NODE_VERSION
  stage: build
  tags: ['cv']
  environment: ${WORK_ENVIRONMENT}-build-$APP_NAME
  cache:
    key: '${PROJECT_SLUG}-${CI_COMMIT_REF_SLUG}-${CI_JOB_STAGE}'
    paths:
      - myroom/node_modules/
    policy: pull-push
  script:
    - cd myroom
    - yarn install
    - CI=false yarn workspace editor-app build
  artifacts:
    paths:
      - myroom/apps/editor-app/dist

# myroom editor
build-myroom-editor:
  <<: *node-myroom-editor-build

########################################
# deploy
########################################
.deploy-web-editor: &deploy-web-editor
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: ['']
  tags: ['cv']
  environment: ${WORK_ENVIRONMENT}-deploy-$APP_NAME
  script:
    - aws s3 cp --region $AWS_S3_REGION --recursive myroom/apps/editor-app/dist s3://${AWS_S3_BUCKET_NAME}/${WORK_ENVIRONMENT}/web-editor

# deploy myroom
deploy-myroom-editor:
  <<: *deploy-web-editor
  environment: $WORK_ENVIRONMENT
  variables:
    AWS_ACCESS_KEY_ID: $DOCS_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $DOCS_AWS_SECRET_ACCESS_KEY
    AWS_S3_REGION: $DOCS_AWS_S3_REGION
    #AWS_S3_PATH: ${DOCS_AWS_S3_PATH}
    APP_NAME: web-editor
  needs:
    - build-myroom-editor

workflow:
  rules:
    - if: '$CI_COMMIT_REF_SLUG == "main"'
      when: always
      variables:
        WORK_ENVIRONMENT: 'dev'
    - if: '$CI_COMMIT_REF_SLUG == "ir-production"'
      when: always
      variables:
        WORK_ENVIRONMENT: 'ir'
