// Don't fix me. Generated by DataTable Extractor.

export enum EItemCategory1 {
	AVATAR = 11, 	//아바타의 외형을 이루는 아이템
	MYROOMSKIN = 12, 	//마이룸의 벽과 바닥을 이루는 스킨 아이템
	MYROOMITEM = 13, 	//마이룸에 배치되는 아이템
	MYROOMCOORDI = 14, 	//완성된 마이룸 제공
	DUMMY01 = 15, 	//-
	SYSTEMITEM = 16, 	//시스템 상으로 구현이 필요한 아이템의 경우 사용함
	STATUSANIMATION = 17, 	//상태메시지 애니메이션
	SYSTEMPURCHASE = 18, 	//시스템 상으로 결제가 필요한 경우 사용함
	PROFILE = 19, 	//유저 프로필 관련
}

export enum EItemCategory2 {
	HEAD = 1111, 	//아바타의 머리 외형 변경
	BODY = 1112, 	//아바타의 몸통 외형 변경
	INDOOR = 1211, 	//실내형 마이룸 스킨
	OUTDOOR = 1212, 	//실외형 마이룸 스킨
	ENVLIGHT = 1221, 	//마이룸 조명
	FLOOR = 1311, 	//바닥에 배치되는 아이템
	WALL = 1312, 	//벽에 배치되는 아이템
	RUG = 1313, 	//마이룸 바닥에 배치되는 바닥 깔개
	INDOORCOORDI = 1411, 	//실내형 코디 완성
	OUTDOORCOORDI = 1412, 	//실외형 코디 완성
	DUMMY02_01 = 1511, 	//-
	DUMMY02_02 = 1512, 	//-
	SYSTEMAVATAR = 1611, 	//머리와 몸통을 포함한 프리셋 정보
	SYSTEMMYROOM = 1621, 	//마이룸의 시스템 설정
	STATUSANIMATIONSUB = 1711, 	//의미없는 상태값
	CONTENTSPURCHASE = 1811, 	//컨텐츠 사용료
	PROFILEITEM = 1911, 	//프로필에 사용할 아이템
}

export enum EItemCategory3 {
	HAIR = 111111, 	//머리 스타일
	HEADACC = 111112, 	//머리 장신구
	EYEBALL = 111113, 	//눈동자 디자인
	CLOTHES = 111211, 	//몸통의 형태
	COSTUME = 111212, 	//몸 전체를 바꿔 입는 한가지 복장
	SINGLEROOM = 121111, 	//가장 많이 쓰일 실내형 벽 2개인 마이룸 스킨
	DUPLEXROOM = 121112, 	//실내형 스킨에 플로어가 2개인 마이룸 스킨
	GARDEN = 121211, 	//필드형 스킨
	FACADE = 121212, 	//왼쪽 벽만 있는 실외 스킨
	MYROOMLIGHT = 122111, 	//마이룸 스킨의 환경맵
	STATUE = 131111, 	//바닥위 O 아이템 위 X 벽에 X | 자신 위에 올리기 X 자신 옆에  X
	FUNITURE = 131112, 	//바닥위 O 아이템 위 X 벽에 X | 자신 위에 올리기 O 자신 옆에  X
	STACKABLE = 131113, 	//바닥위 O 아이템 위 O 벽에 X | 자신 위에 올리기 O 자신 옆에  X
	PILLAR = 131114, 	//바닥위 O 아이템 위 X 벽에 X | 자신 위에 올리기 X 자신 옆에  O
	PROP = 131115, 	//바닥위 O 아이템 위 O 벽에 X | 자신 위에 올리기 X 자신 옆에  X
	WALLHANGING = 131211, 	//바닥위 X 아이템 위 X 벽에 O | 자신 위에 올리기 X 자신 옆에  X
	TABLEMAT = 131311, 	//오직 바닥에만 설치 가능한 아이템.
	FIGURE = 131116, 	//팔로잉 하는 대상의 피규어 목록
	INDOORCOORDITEMPLETE = 141111, 	//실내형 코디 완성
	OUTDOORCOORDITEMPLETE = 141211, 	//실외형 코디 완성
	DUMMY03_01 = 151111, 	//-
	DUMMY03_02 = 151211, 	//-
	AVATERPRESET = 161111, 	//머리와 몸통을 포함한 프리셋 정보
	NPC = 161112, 	//매니페스트로 조합된 아바타형태의 아이템
	SYSTEMMYROOMEMV = 162111, 	//마이룸 코디의 환경설정 값
	MYROOMINDICATOR = 162112, 	//아이템의 상태값을 보여줄 무언가를 위한 시스템 아이템 162112 <<--아직 등록되면 안됨!!!
	STATUSFEEL = 171111, 	//상태메시지애니메이션
	BALLOON = 181111, 	//풍선 결제
	PROFILECARD = 191111, 	//프로필 카드 리소스 및 정의
}

export enum ECroptype {
	None = 0, 	//출력 없음
	Square = 1, 	//화면 비 1:1
	rectangle_9_16 = 2, 	//화면비 세로형  HD
	rectangle_16_9 = 3, 	//화면비 가로형  HD
	rectangle_3_4 = 4, 	//화면비 세로형  SD
	rectangle_4_3 = 5, 	//화면비 가로형  SD
}

export enum EManifestType {
	NONE = 0, 	//매니페스트 수동 생성 입력
	MODEL = 1, 	//매니페스트 모델 타입 자동 생성
	BALLOON = 2, 	//벌룬 더미 매니페스트 생성
}

export enum EFuntionType {
	NONE = 0, 	//기능 없음
	HAVELINK = 1, 	//아이템 테이블에 외부 링크를 가지고 있음. 배치모드에서 변경 불가
	HAVELINKANDIMAGE = 2, 	//아이템 테이블에 이미지 링크를 가지고 있음. 배치모드에서 변경 불가
	HAVELINKANDMOVIE = 3, 	//아이템 테이블에 영상 링크를 가지고 있음. 배치모드에서 변경 불가
	LINK = 4, 	//링크를 넣을 수 있음
	LINKANDIMAGE = 5, 	//링크와 이미지를 넣을 수 있음
	LINKANDMOVIE = 6, 	//링크와 영상을 넣을 수 있음
	LINKANDMEDIA = 7, 	//링크와 이미지 또는 영상을 넣을 수 있음
	DIALOG = 8, 	//대화 기능
	SHOWUI3DGALLERY = 9, 	//선택된 아이템이 가진 갤러리 아이디를 띄운다.
	SHOWUI3DITEM = 10, 	//선택된 아이템이 가진 갤러리 아이디를 띄운다.
	NPCCHATBUBBLE = 11, 	//카메라 방향으로 계속 바라보고, 터치시 액션과 함께 말풍선 띄움
}

export enum EPlacementAttachType {
	None = 0, 	//아이템 이외
	Floor = 1, 	//바닥에 둘 수 있음
	Wall = 2, 	//벽에 붙일 수 있음
	Desk = 3, 	//바닥, 책상에 올릴 수 있음 
	Carpet = 4, 	//카펫
}

export enum ECurrencyType {
	NONE = 0, 	//커런시 없음
	HARDCURRENCY = 100, 	//다이아
	SOFTCURRENCY1 = 200, 	//큐브
	SOFTCURRENCY2 = 300, 	//소프트커런시 2
	SOFTCURRENCY3 = 400, 	//소프트커런시 3
}

export enum EPriceType {
	NOTFORSALE = 1, 	//비매품
	FREE = 2, 	//무료
	SOFTCURRENCY = 3, 	//큐브
	HARDCURRENCY = 4, 	//다이아
	SOFTCURRENCY2 = 5, 	//소프트 커런시 2
	SOFTCURRENCY3 = 6, 	//소프트 커런시 3
}

export enum ERewardType {
	FREEHARDCURRENCY = 1, 	//free 하드커런시
	PAIDHARDCURRENCY = 2, 	//paid 하드커런시
	SOFTCURRENCY1 = 3, 	//소프트커런시 1
	SOFTCURRENCY2 = 4, 	//소프트커런시 2
	SOFTCURRENCY3 = 5, 	//소프트커런시 3
	ITEM = 6, 	//아이템
}

export enum ESaleStatus {
	NONE = 0, 	//판매하는 상품이 아님
	ONSALE = 1, 	//아이템/애셋을 판매중인 상태
	STOPSALE = 2, 	//아이템/애셋이 신고를 통해 판매가 중지된 상태
	JUDGING = 3, 	//아이템/애셋을 판매 요청한 상태
	LICENSED = 4, 	//아이템/애셋이 심사를 통과해 판매가 가능한 상태
}

