// Don't fix me. Generated by DataTable Extractor.

import { EItemCategory1 } from "./System_Enum";
import { EItemCategory2 } from "./System_Enum";
import { EItemCategory3 } from "./System_Enum";
import { ESaleStatus } from "./System_Enum";
import { EPriceType } from "./System_Enum";
import { EPlacementAttachType } from "./System_Enum";
import { EFuntionType } from "./System_Enum";
import { EManifestType } from "./System_Enum";
import { ECurrencyType } from "./System_Enum";

export interface ItemData {
	ID: string,
	use_status: string,
	title: string,
	desc: string,
	hashtag: string[],
	category1: EItemCategory1,
	category2: EItemCategory2,
	category3: EItemCategory3,
	sale_status: ESaleStatus,
	price_type: EPriceType,
	price_amount: number,
	client_itemid: string,
	placement_attach_type: EPlacementAttachType,
	sw: number,
	sh: number,
	useGrids: string[],
	funtion: EFuntionType,
	link_address: string,
	funtion_address: string,
}

export interface ItemCategory1 {
	ID: string,
	Name: string,
	Text: string,
	Desc: string,
	ActiveIcon: string,
}

export interface ItemCategory2 {
	ID: string,
	Name: string,
	Text: string,
	Desc: string,
	Parent: string,
	ActiveIcon: string,
	IsShow: string,
}

export interface ItemCategory3 {
	ID: string,
	Name: string,
	Text: string,
	Desc: string,
	Parent: string,
	ActiveIcon: string,
	Option: string,
	IsShowShop: boolean,
	HideWhenEquipped: string,
	CameraRatio: string,
	ManifestType: EManifestType,
	SvnFolder: string,
	GenerateThumbnail: boolean,
	localKey: string,
}

export interface CurrencyType {
	ID: string,
	Name: string,
	Desc: string,
	IsPaidCurrency: boolean,
}

export interface PriceType {
	ID: string,
	Name: string,
	Desc: string,
	CurrencyType: ECurrencyType,
}

export interface BalloonGrade {
	ID: string,
	BalloonGradeWeight: number,
}

export interface BalloonResource {
	ID: string,
	use_status: string,
	title: string,
	category1: EItemCategory1,
	category2: EItemCategory2,
	category3: EItemCategory3,
	BalloonGradeID: number,
	BalloonLetterBG: string,
	sale_status: ESaleStatus,
	price_type: EPriceType,
	price_amount: number,
	client_itemid: string,
}

export interface CameraSetting {
	ID: string,
	Name: string,
	DefaultZoom: number,
	MaxZoomOut: number,
	MaxZoomIn: number,
	FieldOfView: number,
	Alpha: number,
	Beta: number,
	LowerAlphaLimit: number,
	UpperAlphaLimit: number,
	LowerBetaLimit: number,
	UpperBetaLimit: number,
	UsePanning: boolean,
	LowerAlphaLimitAtFocus: number,
	UpperAlphaLimitAtFocus: number,
	FixToBottom: boolean,
	OffsetY: number,
}

export interface OutSide {
	ID: string,
	X: number,
	Y: number,
	Z: number,
}

export interface ItemGrid {
	ID: string,
	gridWidth: number,
	gridHeight: number,
	gridOrigin: number[],
	gridMarkArray: number[],
}

export interface DialogMain {
	ID: string,
	TitleLocalKey: string,
	StartLocalKey: string,
	FirstDialogTextID: string,
	TellerModelItemID: string,
	ShowResult: boolean,
	BackGroundImageVideo: string,
	TitleButtonLocalKey: string,
	TitleImageName: string,
	TestShareLocalKey: string,
	TestRetryLocalKey: string,
	ResultShareLocalKey: string,
}

export interface DialogText {
	ID: string,
	DialogMainID: string,
	TellerType: string,
	LocalKey: string,
	NextID: string,
	AnswerID: string[],
	AnimationItemID: string,
	AnswerScore: number,
}

export interface DialogResult {
	ID: string,
	DialogMainID: string,
	MinScore: number,
	MaxScore: number,
	ResultURL: string,
	ResultImageName: string,
	ResultAnimationItemID: string,
	ResultSubTitle0LocalKey: string,
	ResultMainTitle0LocalKey: string,
	ResultSubTitle1LocalKey: string,
	ResultMainTitle1LocalKey: string,
	ResultText1LocalKey: string,
	ResultSubTitle2LocalKey: string,
	ResultMainTitle2LocalKey: string,
	ResultText2LocalKey: string,
}

export interface WebConstant {
	ID: string,
	Value: string,
	DataType: string,
	Desc: string,
}

export interface WebColors {
	ID: string,
	hex: string,
}

export interface SkinColors {
	ID: string,
	hexui: string,
	hex3D: string,
}

export interface HairColors {
	ID: string,
	hexui: string,
	hex3D: string,
}

export interface ItemMetaData {
	Key: string,
	ItemStructName: string,
}

