// Don't fix me. Generated by DataTable Extractor.

export class C_WebConstant {
	public static readonly string:string = "string"; 	//string
	public static readonly PHOTO_LIMIT_VALUE:number = 50; 	//(M)
	public static readonly SAMPLE_STRING:string = "testString2"; 	//aswefsef
	public static readonly SAMPLE_NUMBER_ARR:number[] = [1, 2, 3]; 	//eeeee
	public static readonly SAMPLE_STRING_ARR:string[] = ["sdf", "asdf", "adsf"]; 	//
	public static readonly SAMPLE_BOOLEAN:boolean = false; 	//
	public static readonly EMPTY_PHOTO_LIMIT_VALUE:number = 0; 	//(M)
	public static readonly EMPTY_SAMPLE_STRING:string = ""; 	//aswefsef
	public static readonly EMPTY_SAMPLE_NUMBER_ARR:number[] = []; 	//eeeee
	public static readonly EMPTY_SAMPLE_STRING_ARR:string[] = []; 	//
	public static readonly EMPTY_SAMPLE_BOOLEAN:boolean = false; 	//
	public static readonly OUTSIDE_FIGURE_LIMITS:number = 8; 	//전체 피규어
	public static readonly OUTSIDE_FIGURE_RECOMMEND:number = 4; 	//추천 피규어
	public static readonly OUTSIDE_FIGURE_POPULAR:number = 4; 	//인기 피규어
	public static readonly OUTSIDE_FIGURE_SIZE:number = 0.75; 	//아웃사이드 피규어 사이즈
	public static readonly INMYROOM_FIGURE_SIZE:number = 0.5; 	//마이룸내 피규어 사이즈
	public static readonly INMYROOM_RECYCLE_MAXCOUNT:number = 100; 	//마이룸 내 휴지통 최대 수용량
	public static readonly INMYROOM_ITEM_MOVEMENT_GRID_POSITION:number[] = [1, 1, 1]; 	//선택된 포인트에서 아이템 그리드 까지의 x,y,z축 길이
	public static readonly INMYROOM_ITEM_MOVEMENT_PIVOT_POSITION:number[] = [1, 1, 1]; 	//아이템 그리드 에서 아이템 까지의 x,y,z축 길이
}

