stages:
  - test
  - build
  - deploy

variables:
  NODE_VERSION: 16.16.0
  WORK_ENVIRONMENT: $CI_COMMIT_REF_SLUG

########################################
# build
########################################
.storybook-build: &node-build
  image: node:$NODE_VERSION
  stage: build
  tags: ['cv']
  environment: ${WORK_ENVIRONMENT}-build-$APP_NAME
  cache:
    key: '${PROJECT_SLUG}-${CI_COMMIT_REF_SLUG}-${CI_JOB_STAGE}'
    paths:
      - myroom/apps/web-app/node_modules/
    policy: pull-push
  script:
    - cd myroom/apps/web-app
    - yarn install
    - CI=false yarn build-storybook
  artifacts:
    paths:
      - myroom/apps/web-app/storybook-static

# myroom
build-myroom-storybook:
  <<: *node-build

########################################
# deploy
########################################
.deploy-web: &deploy-web
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: ['']
  tags: ['cv']
  environment: ${WORK_ENVIRONMENT}-deploy-$APP_NAME
  script:
    - aws s3 cp --region $AWS_S3_REGION --recursive myroom/apps/web-app/storybook-static s3://${AWS_S3_BUCKET_NAME}/${WORK_ENVIRONMENT}/web-myroom/storybook

# deploy myroom
deploy-myroom-storybook:
  <<: *deploy-web
  environment: $WORK_ENVIRONMENT
  variables:
    AWS_ACCESS_KEY_ID: $DOCS_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $DOCS_AWS_SECRET_ACCESS_KEY
    AWS_S3_REGION: $DOCS_AWS_S3_REGION
    APP_NAME: web-myroom-storybook
  needs:
    - build-myroom-storybook

workflow:
  rules:
    - if: '$CI_COMMIT_REF_SLUG == "main"'
      when: always
      variables:
        WORK_ENVIRONMENT: 'dev'
    - if: '$CI_COMMIT_REF_SLUG == "ir-production"'
      when: always
      variables:
        WORK_ENVIRONMENT: 'ir'
